name: Deploy Docker to EC2

on:
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image locally (test)
        run: docker pull ${{ secrets.DOCKER_IMAGE }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop old container if exists
            docker stop test-app || true
            docker rm test-app || true

            # Pull latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_IMAGE }}

            # Run container
            # Run nginx (simple web server)
            docker run -d --name test-app -p 80:80 nginx:latest

