# idea hear is 2 files will be created on ec2 at time of creating Instance on AWS namely "docker-compose.yml" and "deploy.sh"
# at time of new version deployment via git, git Actions just run the second file i.e "deploy.sh" and docker container gors live
# tihs facalitate roll back if new verion get failed or creashed... 
# roll back will be from administrator terminal after cinnection to ec2 via ssh
name: Deploy Frontend & Backend to EC2

on:
  workflow_run:
    workflows: ["Docker CI/CD"]
    types:
      -completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app   # adjust to your deploy path
            ./deploy.sh
