# This gitAction workflow login to organizations docker hub and pushes the latest frontend and backend docker image
# to docker hub ... 
# it uses latest model tag so that when EC2 pulls it always pulls the latest model
# in try to implement roolback we use SHA tags to push along with dates so, if the latest deployment doesn't funtion 
# well we can roll back to stable image

name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Extract metadata
        id: meta
        run: |
          echo "sha_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "build_time=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      # Build local images
      - name: Build backend image
        run: docker build -t backend:test ./backend

      - name: Build frontend image
        run: docker build -t frontend:test ./frontend
        
      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push backend
      - name: Build & push backend (prod)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            shad1811/backend:latest
            shad1811/backend:${{ env.sha_tag }}

      # Build & push frontend
      - name: Build & push frontend (prod)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            shad1811/frontend:latest
            shad1811/frontend:${{ env.sha_tag }}
